### ISSUE TITLE
RPI4 - Raspbian- Buster - raspberrypi - LIMESDR

### ISSUE THREAD

**Issue by jacooooooooool** [emvivre/limesdr_toolbox#4]
pi@raspberrypi:~/limesdr_toolbox $ make
Scanning dependencies of target limesdr_send
[  9%] Building C object CMakeFiles/limesdr_send.dir/limesdr_send.c.o
[ 18%] Building C object CMakeFiles/limesdr_send.dir/limesdr_util.c.o
[ 27%] Linking C executable limesdr_send
[ 27%] Built target limesdr_send
Scanning dependencies of target limesdr_stopchannel
[ 36%] Building C object CMakeFiles/limesdr_stopchannel.dir/limesdr_stopchannel.c.o
[ 45%] Linking C executable limesdr_stopchannel
[ 45%] Built target limesdr_stopchannel
Scanning dependencies of target limesdr_forward
[ 54%] Building C object CMakeFiles/limesdr_forward.dir/limesdr_forward.c.o
[ 63%] Building C object CMakeFiles/limesdr_forward.dir/limesdr_util.c.o
[ 72%] Linking C executable limesdr_forward
[ 72%] Built target limesdr_forward
Scanning dependencies of target limesdr_dump
[ 81%] Building C object CMakeFiles/limesdr_dump.dir/limesdr_dump.c.o
[ 90%] Building C object CMakeFiles/limesdr_dump.dir/limesdr_util.c.o
[100%] Linking C executable limesdr_dump
[100%] Built target limesdr_dump

REBOOT

 SoapySDRUtil --find
######################################################
######################################################

Found device 0
  addr = 24607:1027
  driver = lime
  label = LimeSDR Mini [USB 3.0] 1xx76xxx99xx3
  media = USB 3.0
  module = FT601
  name = LimeSDR Mini
  serial = 1xx76xxx99xx3

-------->

pi@raspberrypi:~/limesdr_toolbox $ LimeUtil --find
  * [LimeSDR Mini, media=USB 3.0, module=FT601, addr=24607:1027, serial=1xx76xxx99xx3]

------>

pi@raspberrypi:~/limesdr_toolbox $ sudo ./limesdr_dump -f 100.1e6 -o out.dat
Reference clock 40.00 MHz
Invalid channel number.
LMS_EnableChannel() :
libusb: warning [libusb_exit] application left some devices open

--------->

pi@raspberrypi:~/limesdr_toolbox $ sudo ./limesdr_dump -c 2 -f 100.1e6 -o out.dat
pi@raspberrypi:~/limesdr_toolbox $ sudo ./limesdr_dump -c 2 -C 2 -f 100.1e6 -o out.dat

 Reference clock 40.00 MHz
Invalid channel number.
LMS_EnableChannel() :
libusb: warning [libusb_exit] application left some devices open

help :)

**Comment by emvivre** [comment]
Hello jacekcorek, thanks you for your comment.
I commit a patch recently. It should works now :)

**Comment by jacooooooooool** [comment]
Thanks: ) fantastic soft !!  
            
          
     
      
       
        Dnia 26 stycznia 2020 17:51 emvivre &lt;notifications@github.com&gt; napisał(a):
       
    
       
         Hello jacekcorek, thanks you for your comment.  
I commit a patch recently. It should works now :)
